Data Cleaning

깐부치킨에 대한 매장데이터, 거래데이터, 매장별_상품별 팔린 개수 데이터에 NULL, 0, -1 값이 있는지 확인하고
메뉴명 통일에 관해 어떻게 진행해야할 지 고민해 보기.

In [83]:
import pandas as pd

storeData = pd.read_csv('../processedData/깐부치킨_매장데이터.csv', encoding='UTF8')
receiptData = pd.read_csv('../processedData/깐부치킨_거래데이터.csv', encoding='UTF8')
menuData = pd.read_csv('../processedData/깐부치킨_매장별_상품별 팔린 개수.csv', encoding='UTF8')

In [58]:
receiptData

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
0,S23991,깐부치킨(강남구청역1번출구점),20190202,6,20190202190027,포장1,2000,SIDE MENU,코울슬러,48,1,2000
1,S23991,깐부치킨(강남구청역1번출구점),20190204,14,20190204201731,포장1,19000,SIDE MENU,골뱅이,8,1,19000
2,S23991,깐부치킨(강남구청역1번출구점),20190201,2,20190201175536,포장1,19000,SIDE MENU,골뱅이,8,1,19000
3,S23991,깐부치킨(강남구청역1번출구점),20190201,7,20190201192707,포장1,11000,SIDE MENU,웨지포테이토,12,1,11000
4,S23991,깐부치킨(강남구청역1번출구점),20190203,1,20190203174823,포장1,19000,MAIN MENU,마늘간장,3496,1,19000
...,...,...,...,...,...,...,...,...,...,...,...,...
83912,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,18000,MAIN MENU,바삭한식스팩,1297,1,18000
83913,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,18000,MAIN MENU,불사조,2737,1,18000
83914,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,13500,깐부 청담1,청양고추만두,4086,3,4500
83915,U11422,깐부치킨(청담1),20190228,14,20190228131736,10,8000,깐부 청담1,소고기볶음밥,4072,1,8000
83916,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,8000,깐부 청담1,오렌지치즈샐러드,4085,1,8000

In [ ]:
#NULL 값 확인 -> X

storeData.isnull().sum()
receiptData.isnull().sum()
menuData.isnull().sum()

In [ ]:
minusData = receiptData.loc[receiptData['총판매금액'] <= 0]

In [ ]:
menulistData = menuData.copy()

In [ ]:
pd.set_option('display.max_rows', None) 
menulistData

In [ ]:
del menulistData['매장코드']
del menulistData['매장명']
del menulistData['판매개수']

In [ ]:
menulistData[menulistData['상품명']=='생맥주 500cc']
menulistData[menulistData['상품명']=='생맥주500cc']

In [ ]:
ddmenulistData = menulistData.drop_duplicates()

In [ ]:
pd.set_option('display.max_rows', None) 
menulistData.sort_values(by=["소분류명", "상품명", "상품코드"], ascending=[True, True, True])

In [ ]:
ddmenulistData.sort_values(by=["소분류명", "상품명", "상품코드"], ascending=[True, True, True])

In [62]:
pd.set_option('display.max_rows', None) 
maxmenuData = menuData[menuData['매장코드'] == 'T06644']
maxmenuData[maxmenuData['소분류명'] == 'MAIN MENU'].sort_values(by=["소분류명", "상품명", "상품코드"], ascending=[True, True, True])

        매장코드         매장명       소분류명        상품명  상품코드   판매단가  판매개수
1244  T06644  (주)깐부 청담본점  MAIN MENU       고추간장  2118  18000    96
1238  T06644  (주)깐부 청담본점  MAIN MENU       마늘간장  3496  19000   120
1243  T06644  (주)깐부 청담본점  MAIN MENU   마늘간장(순살)  4096  19000    96
1258  T06644  (주)깐부 청담본점  MAIN MENU  마늘간장윙봉크런치  3492  19000    62
1241  T06644  (주)깐부 청담본점  MAIN MENU     마늘전기구이  2121  17000   103
1234  T06644  (주)깐부 청담본점  MAIN MENU     바삭한식스팩  1297  18000   138
1254  T06644  (주)깐부 청담본점  MAIN MENU        불사조  2737  18000    74
1274  T06644  (주)깐부 청담본점  MAIN MENU   불사조윙봉크런치  3493  19000    20
1255  T06644  (주)깐부 청담본점  MAIN MENU        불파스  3269  25000    74
1237  T06644  (주)깐부 청담본점  MAIN MENU       순살스윗  2119  18000   120
1227  T06644  (주)깐부 청담본점  MAIN MENU     순살크리스피  2736  18000   243
1250  T06644  (주)깐부 청담본점  MAIN MENU       순살파닭    28  18000    81
1239  T06644  (주)깐부 청담본점  MAIN MENU      윙봉크런치  3491  18000   108
1263  T06644  (주)깐부 청담본점  MAIN MENU       유린치킨  1851  18000    39
1252  T06644  (주)깐부 청담본점  MAIN MENU       전기구이  2120  15000    78
1232  T06644  (주)깐부 청담본점  MAIN MENU       크리스피  3495  18000   156
1245  T06644  (주)깐부 청담본점  MAIN MENU    크리스피 반반  3500  19000    89
1282  T06644  (주)깐부 청담본점  MAIN MENU    크리스피 양념  3499  19500     5
1230  T06644  (주)깐부 청담본점  MAIN MENU       후라이드  3494  17000   165
1256  T06644  (주)깐부 청담본점  MAIN MENU    후라이드 반반  3498  18000    67
1276  T06644  (주)깐부 청담본점  MAIN MENU    후라이드 양념  3497  18500    16

In [61]:
menuData[menuData['매장코드'] == 'U11422'][menuData['소분류명'] == 'MAIN MENU']

<ipython-input-61-cbaa5fee2d69>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  menuData[menuData['매장코드'] == 'U11422'][menuData['소분류명'] == 'MAIN MENU']

        매장코드        매장명       소분류명        상품명  상품코드   판매단가  판매개수
1842  U11422  깐부치킨(청담1)  MAIN MENU    후라이드 양념  3497  18500     1
1843  U11422  깐부치킨(청담1)  MAIN MENU        불사조  2737  18000     1
1847  U11422  깐부치킨(청담1)  MAIN MENU  마늘간장윙봉크런치  3492  19000     1
1848  U11422  깐부치킨(청담1)  MAIN MENU       후라이드  3494  17000     1
1849  U11422  깐부치킨(청담1)  MAIN MENU     바삭한식스팩  1297  18000     1
1851  U11422  깐부치킨(청담1)  MAIN MENU     후라이드양념  1750  18000     0

In [63]:
#menuData.iloc[menuData['상품명']=='후라이드양념'][1851]
menuData['상품명'][1851] = '후라이드 양념'

<ipython-input-63-8a68fa567790>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  menuData['상품명'][1851] = '후라이드 양념'

In [64]:
menuData[menuData['매장코드'] == 'U11422'][menuData['소분류명'] == 'MAIN MENU']

<ipython-input-64-cbaa5fee2d69>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  menuData[menuData['매장코드'] == 'U11422'][menuData['소분류명'] == 'MAIN MENU']

        매장코드        매장명       소분류명        상품명  상품코드   판매단가  판매개수
1842  U11422  깐부치킨(청담1)  MAIN MENU    후라이드 양념  3497  18500     1
1843  U11422  깐부치킨(청담1)  MAIN MENU        불사조  2737  18000     1
1847  U11422  깐부치킨(청담1)  MAIN MENU  마늘간장윙봉크런치  3492  19000     1
1848  U11422  깐부치킨(청담1)  MAIN MENU       후라이드  3494  17000     1
1849  U11422  깐부치킨(청담1)  MAIN MENU     바삭한식스팩  1297  18000     1
1851  U11422  깐부치킨(청담1)  MAIN MENU    후라이드 양념  1750  18000     0

In [65]:
pd.options.display.max_rows = 60
pd.options.display.max_columns = 20

receiptData #menuData[menuData['매장코드'] == 'U11422'][menuData['소분류명'] == 'MAIN MENU']

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
0,S23991,깐부치킨(강남구청역1번출구점),20190202,6,20190202190027,포장1,2000,SIDE MENU,코울슬러,48,1,2000
1,S23991,깐부치킨(강남구청역1번출구점),20190204,14,20190204201731,포장1,19000,SIDE MENU,골뱅이,8,1,19000
2,S23991,깐부치킨(강남구청역1번출구점),20190201,2,20190201175536,포장1,19000,SIDE MENU,골뱅이,8,1,19000
3,S23991,깐부치킨(강남구청역1번출구점),20190201,7,20190201192707,포장1,11000,SIDE MENU,웨지포테이토,12,1,11000
4,S23991,깐부치킨(강남구청역1번출구점),20190203,1,20190203174823,포장1,19000,MAIN MENU,마늘간장,3496,1,19000
...,...,...,...,...,...,...,...,...,...,...,...,...
83912,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,18000,MAIN MENU,바삭한식스팩,1297,1,18000
83913,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,18000,MAIN MENU,불사조,2737,1,18000
83914,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,13500,깐부 청담1,청양고추만두,4086,3,4500
83915,U11422,깐부치킨(청담1),20190228,14,20190228131736,10,8000,깐부 청담1,소고기볶음밥,4072,1,8000
83916,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,8000,깐부 청담1,오렌지치즈샐러드,4085,1,8000

In [66]:
pd.options.display.max_rows = 60
pd.options.display.max_columns = 20

receiptData = receiptData.sort_values(by = ['매장코드', '소분류명'], ignore_index=True)
receiptData

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
0,S23991,깐부치킨(강남구청역1번출구점),20190203,1,20190203174823,포장1,19000,MAIN MENU,마늘간장,3496,1,19000
1,S23991,깐부치킨(강남구청역1번출구점),20190201,7,20190201192707,포장1,19000,MAIN MENU,마늘간장,3496,1,19000
2,S23991,깐부치킨(강남구청역1번출구점),20190203,12,20190203220406,포장1,18000,MAIN MENU,크리스피,3495,1,18000
3,S23991,깐부치킨(강남구청역1번출구점),20190201,30,20190201230947,포장1,17000,MAIN MENU,후라이드,3494,1,17000
4,S23991,깐부치킨(강남구청역1번출구점),20190201,20,20190201211828,포장1,17000,MAIN MENU,후라이드,3494,1,17000
...,...,...,...,...,...,...,...,...,...,...,...,...
83912,U11422,깐부치킨(청담1),20190215,24,20190215130516,1,-3000,점심,아메리카노 HOT,2994,-1,3000
83913,U11422,깐부치킨(청담1),20190215,23,20190215130346,1,3000,점심,아메리카노 HOT,2994,1,3000
83914,U11422,깐부치킨(청담1),20190214,15,20190214144855,1,12000,점심,아메리카노 HOT,2994,4,3000
83915,U11422,깐부치킨(청담1),20190225,1,20190225112402,1,3000,점심,아메리카노 HOT,2994,1,3000
83916,U11422,깐부치킨(청담1),20190221,8,20190221192730,1,9000,점심,아메리카노 HOT,2994,3,3000

In [67]:
receiptData[receiptData['매장코드'] == 'U11422'][receiptData['소분류명'] == '깐부 청담1'] #83578 : 83917

<ipython-input-67-5fa11e60857d>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  receiptData[receiptData['매장코드'] == 'U11422'][receiptData['소분류명'] == '깐부 청담1'] #83578 : 83917

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
83587,U11422,깐부치킨(청담1),20190201,7,20190201181631,1,4500,깐부 청담1,청양고추만두,4086,1,4500
83588,U11422,깐부치킨(청담1),20190201,7,20190201181631,1,8000,깐부 청담1,묵은지 치킨라면,4067,1,8000
83589,U11422,깐부치킨(청담1),20190201,3,20190201115856,1,18000,깐부 청담1,피자치킨까스,4074,2,9000
83590,U11422,깐부치킨(청담1),20190201,7,20190201181631,1,9000,깐부 청담1,칠리치즈펜네파스타,4081,1,9000
83591,U11422,깐부치킨(청담1),20190201,1,20190201102809,1,4800,깐부 청담1,노아(크러쉬드애플주스),4061,1,4800
...,...,...,...,...,...,...,...,...,...,...,...,...
83901,U11422,깐부치킨(청담1),20190228,11,20190228125458,9,8000,깐부 청담1,돈까스,4077,1,8000
83902,U11422,깐부치킨(청담1),20190228,13,20190228131658,9,6500,깐부 청담1,유부우동,4068,1,6500
83903,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,13500,깐부 청담1,청양고추만두,4086,3,4500
83904,U11422,깐부치킨(청담1),20190228,14,20190228131736,10,8000,깐부 청담1,소고기볶음밥,4072,1,8000
83905,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,8000,깐부 청담1,오렌지치즈샐러드,4085,1,8000

In [71]:
pd.set_option('display.max_rows', None) 
a = list(range(83587, 83917))

# receiptData[receiptData['매장코드'] == 'U11422']

dropreceiptData = receiptData.drop(a , axis=0)
dropreceiptData[dropreceiptData['매장코드'] == 'U11422']

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
83577,U11422,깐부치킨(청담1),20190225,4,20190225114749,1,19000,MAIN MENU,마늘간장윙봉크런치,3492,1,19000
83578,U11422,깐부치킨(청담1),20190227,14,20190227133312,1,18500,MAIN MENU,후라이드 양념,3497,1,18500
83579,U11422,깐부치킨(청담1),20190227,14,20190227133312,1,17000,MAIN MENU,후라이드,3494,1,17000
83580,U11422,깐부치킨(청담1),20190227,13,20190227133042,2,-18000,MAIN MENU,후라이드양념,1750,-1,18000
83581,U11422,깐부치킨(청담1),20190227,11,20190227132406,2,18000,MAIN MENU,후라이드양념,1750,1,18000
83582,U11422,깐부치킨(청담1),20190227,13,20190227133042,2,-16000,MAIN MENU,후라이드,2113,-1,16000
83583,U11422,깐부치킨(청담1),20190227,11,20190227132406,2,16000,MAIN MENU,후라이드,2113,1,16000
83584,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,18000,MAIN MENU,바삭한식스팩,1297,1,18000
83585,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,18000,MAIN MENU,불사조,2737,1,18000
83586,U11422,깐부치킨(청담1),20190226,10,20190226140046,2,12000,SIDE MENU,순살국물떡볶이,2456,1,12000

In [72]:
# pd.set_option('display.max_rows', None) 
pd.options.display.max_rows = 60
pd.options.display.max_columns = 20

print(len(a))
dropreceiptData

330

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
0,S23991,깐부치킨(강남구청역1번출구점),20190203,1,20190203174823,포장1,19000,MAIN MENU,마늘간장,3496,1,19000
1,S23991,깐부치킨(강남구청역1번출구점),20190201,7,20190201192707,포장1,19000,MAIN MENU,마늘간장,3496,1,19000
2,S23991,깐부치킨(강남구청역1번출구점),20190203,12,20190203220406,포장1,18000,MAIN MENU,크리스피,3495,1,18000
3,S23991,깐부치킨(강남구청역1번출구점),20190201,30,20190201230947,포장1,17000,MAIN MENU,후라이드,3494,1,17000
4,S23991,깐부치킨(강남구청역1번출구점),20190201,20,20190201211828,포장1,17000,MAIN MENU,후라이드,3494,1,17000
...,...,...,...,...,...,...,...,...,...,...,...,...
83582,U11422,깐부치킨(청담1),20190227,13,20190227133042,2,-16000,MAIN MENU,후라이드,2113,-1,16000
83583,U11422,깐부치킨(청담1),20190227,11,20190227132406,2,16000,MAIN MENU,후라이드,2113,1,16000
83584,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,18000,MAIN MENU,바삭한식스팩,1297,1,18000
83585,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,18000,MAIN MENU,불사조,2737,1,18000
83586,U11422,깐부치킨(청담1),20190226,10,20190226140046,2,12000,SIDE MENU,순살국물떡볶이,2456,1,12000

In [73]:
dropreceiptData[dropreceiptData['매장코드'] == 'S54785'] #S54785	깐부치킨(청담1호점)

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
44056,S54785,깐부치킨(청담1호점),20190203,20,20190203222510,포장3,300,EXTRA MENU,추가,3232,1,300
44057,S54785,깐부치킨(청담1호점),20190208,13,20190208212747,포장1,600,EXTRA MENU,추가,3232,2,300
44058,S54785,깐부치킨(청담1호점),20190220,25,20190220225608,10,300,EXTRA MENU,추가,3232,1,300
44059,S54785,깐부치킨(청담1호점),20190220,3,20190220182441,포장1,600,EXTRA MENU,추가,3232,2,300
44060,S54785,깐부치킨(청담1호점),20190221,4,20190221194106,포장1,600,EXTRA MENU,추가,3232,2,300
...,...,...,...,...,...,...,...,...,...,...,...,...
45919,S54785,깐부치킨(청담1호점),20190204,22,20190204221115,5,5000,행사,추가,435,5,1000
45920,S54785,깐부치킨(청담1호점),20190207,17,20190208001051,포장1,7000,행사,추가,435,7,1000
45921,S54785,깐부치킨(청담1호점),20190219,10,20190219212123,야외21,1000,행사,추가,435,1,1000
45922,S54785,깐부치킨(청담1호점),20190224,2,20190224170721,포장2,1000,행사,추가,435,1,1000
45923,S54785,깐부치킨(청담1호점),20190226,27,20190226232252,포장1,1000,행사,추가,435,1,1000

In [74]:
dropreceiptData = dropreceiptData.sort_values(by=['매장코드', '소분류명'])

In [75]:
dropreceiptData[dropreceiptData['매장코드'] == 'U11422']

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
83577,U11422,깐부치킨(청담1),20190225,4,20190225114749,1,19000,MAIN MENU,마늘간장윙봉크런치,3492,1,19000
83578,U11422,깐부치킨(청담1),20190227,14,20190227133312,1,18500,MAIN MENU,후라이드 양념,3497,1,18500
83579,U11422,깐부치킨(청담1),20190227,14,20190227133312,1,17000,MAIN MENU,후라이드,3494,1,17000
83580,U11422,깐부치킨(청담1),20190227,13,20190227133042,2,-18000,MAIN MENU,후라이드양념,1750,-1,18000
83581,U11422,깐부치킨(청담1),20190227,11,20190227132406,2,18000,MAIN MENU,후라이드양념,1750,1,18000
83582,U11422,깐부치킨(청담1),20190227,13,20190227133042,2,-16000,MAIN MENU,후라이드,2113,-1,16000
83583,U11422,깐부치킨(청담1),20190227,11,20190227132406,2,16000,MAIN MENU,후라이드,2113,1,16000
83584,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,18000,MAIN MENU,바삭한식스팩,1297,1,18000
83585,U11422,깐부치킨(청담1),20190228,10,20190228125113,10,18000,MAIN MENU,불사조,2737,1,18000
83586,U11422,깐부치킨(청담1),20190226,10,20190226140046,2,12000,SIDE MENU,순살국물떡볶이,2456,1,12000

In [77]:
for i in range(83577, 83587) : #S54785	깐부치킨(청담1호점)	
    dropreceiptData['매장코드'][i] = 'S54785'
    dropreceiptData['매장명'][i] = '깐부치킨(청담1호점)'
dropreceiptData

<ipython-input-77-041e5f7894f7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dropreceiptData['매장코드'][i] = 'S54785'
<ipython-input-77-041e5f7894f7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dropreceiptData['매장명'][i] = '깐부치킨(청담1호점)'

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
0,S23991,깐부치킨(강남구청역1번출구점),20190203,1,20190203174823,포장1,19000,MAIN MENU,마늘간장,3496,1,19000
1,S23991,깐부치킨(강남구청역1번출구점),20190201,7,20190201192707,포장1,19000,MAIN MENU,마늘간장,3496,1,19000
2,S23991,깐부치킨(강남구청역1번출구점),20190203,12,20190203220406,포장1,18000,MAIN MENU,크리스피,3495,1,18000
3,S23991,깐부치킨(강남구청역1번출구점),20190201,30,20190201230947,포장1,17000,MAIN MENU,후라이드,3494,1,17000
4,S23991,깐부치킨(강남구청역1번출구점),20190201,20,20190201211828,포장1,17000,MAIN MENU,후라이드,3494,1,17000
...,...,...,...,...,...,...,...,...,...,...,...,...
83582,S54785,깐부치킨(청담1호점),20190227,13,20190227133042,2,-16000,MAIN MENU,후라이드,2113,-1,16000
83583,S54785,깐부치킨(청담1호점),20190227,11,20190227132406,2,16000,MAIN MENU,후라이드,2113,1,16000
83584,S54785,깐부치킨(청담1호점),20190228,10,20190228125113,10,18000,MAIN MENU,바삭한식스팩,1297,1,18000
83585,S54785,깐부치킨(청담1호점),20190228,10,20190228125113,10,18000,MAIN MENU,불사조,2737,1,18000
83586,S54785,깐부치킨(청담1호점),20190226,10,20190226140046,2,12000,SIDE MENU,순살국물떡볶이,2456,1,12000

In [78]:
dropreceiptData = dropreceiptData.sort_values(by=['매장코드', '소분류명', '상품명'])

In [79]:
receiptData = dropreceiptData.sort_values(by=['매장코드', '소분류명', '상품명'], ignore_index=True)

In [80]:
receiptData

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
0,S23991,깐부치킨(강남구청역1번출구점),20190204,14,20190204201731,포장1,18000,MAIN MENU,고추간장,2118,1,18000
1,S23991,깐부치킨(강남구청역1번출구점),20190203,3,20190203191830,포장1,18000,MAIN MENU,고추간장,2118,1,18000
2,S23991,깐부치킨(강남구청역1번출구점),20190202,8,20190202191158,7,18000,MAIN MENU,고추간장,2118,1,18000
3,S23991,깐부치킨(강남구청역1번출구점),20190201,22,20190201214234,7,18000,MAIN MENU,고추간장,2118,1,18000
4,S23991,깐부치킨(강남구청역1번출구점),20190203,8,20190203204417,6,18000,MAIN MENU,고추간장,2118,1,18000
...,...,...,...,...,...,...,...,...,...,...,...,...
83582,U06529,깐부치킨(역삼초교점),20190228,20,20190301002504,테이블-9,11000,주류,카스(병),3355,2,5500
83583,U06529,깐부치킨(역삼초교점),20190211,1,20190211190925,테이블-5,6000,주류,클라우드,1286,1,6000
83584,U06529,깐부치킨(역삼초교점),20190213,4,20190213193435,테이블-3,36000,주류,클라우드,1286,6,6000
83585,U06529,깐부치킨(역삼초교점),20190219,6,20190219212814,테이블-1,6000,주류,클라우드,1286,1,6000
83586,U06529,깐부치킨(역삼초교점),20190228,10,20190228212555,테이블-5,12000,주류,클라우드,1286,2,6000

In [81]:
receiptData[receiptData['매장코드'] == 'S54785']

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
44056,S54785,깐부치킨(청담1호점),20190203,20,20190203222510,포장3,300,EXTRA MENU,추가,3232,1,300
44057,S54785,깐부치킨(청담1호점),20190208,13,20190208212747,포장1,600,EXTRA MENU,추가,3232,2,300
44058,S54785,깐부치킨(청담1호점),20190220,25,20190220225608,10,300,EXTRA MENU,추가,3232,1,300
44059,S54785,깐부치킨(청담1호점),20190220,3,20190220182441,포장1,600,EXTRA MENU,추가,3232,2,300
44060,S54785,깐부치킨(청담1호점),20190221,4,20190221194106,포장1,600,EXTRA MENU,추가,3232,2,300
...,...,...,...,...,...,...,...,...,...,...,...,...
45929,S54785,깐부치킨(청담1호점),20190204,22,20190204221115,5,5000,행사,추가,435,5,1000
45930,S54785,깐부치킨(청담1호점),20190207,17,20190208001051,포장1,7000,행사,추가,435,7,1000
45931,S54785,깐부치킨(청담1호점),20190219,10,20190219212123,야외21,1000,행사,추가,435,1,1000
45932,S54785,깐부치킨(청담1호점),20190224,2,20190224170721,포장2,1000,행사,추가,435,1,1000
45933,S54785,깐부치킨(청담1호점),20190226,27,20190226232252,포장1,1000,행사,추가,435,1,1000

In [82]:
receiptData.to_csv('../processedData/깐부치킨_거래데이터.csv', index=False)

In [84]:
receiptData

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
0,S23991,깐부치킨(강남구청역1번출구점),20190204,14,20190204201731,포장1,18000,MAIN MENU,고추간장,2118,1,18000
1,S23991,깐부치킨(강남구청역1번출구점),20190203,3,20190203191830,포장1,18000,MAIN MENU,고추간장,2118,1,18000
2,S23991,깐부치킨(강남구청역1번출구점),20190202,8,20190202191158,7,18000,MAIN MENU,고추간장,2118,1,18000
3,S23991,깐부치킨(강남구청역1번출구점),20190201,22,20190201214234,7,18000,MAIN MENU,고추간장,2118,1,18000
4,S23991,깐부치킨(강남구청역1번출구점),20190203,8,20190203204417,6,18000,MAIN MENU,고추간장,2118,1,18000
...,...,...,...,...,...,...,...,...,...,...,...,...
83582,U06529,깐부치킨(역삼초교점),20190228,20,20190301002504,테이블-9,11000,주류,카스(병),3355,2,5500
83583,U06529,깐부치킨(역삼초교점),20190211,1,20190211190925,테이블-5,6000,주류,클라우드,1286,1,6000
83584,U06529,깐부치킨(역삼초교점),20190213,4,20190213193435,테이블-3,36000,주류,클라우드,1286,6,6000
83585,U06529,깐부치킨(역삼초교점),20190219,6,20190219212814,테이블-1,6000,주류,클라우드,1286,1,6000
83586,U06529,깐부치킨(역삼초교점),20190228,10,20190228212555,테이블-5,12000,주류,클라우드,1286,2,6000