In [153]:
import pandas as pd

data = pd.read_csv('../rawdata/깐부치킨_매장데이터.csv', encoding='UTF8')

In [154]:
CD = sorted(list(set(data['매장코드'])))
CD

['S23991',
 'S23992',
 'S24004',
 'S24023',
 'S24036',
 'S24077',
 'S24088',
 'S24101',
 'S31130',
 'S35539',
 'S36322',
 'S36329',
 'S37219',
 'S41446',
 'S42681',
 'S48814',
 'S49287',
 'S54785',
 'S56417',
 'S70964',
 'S95349',
 'T00602',
 'T06644',
 'T18671',
 'T46063',
 'T50791',
 'T53532',
 'T74630',
 'T78908',
 'T79908',
 'T86552',
 'T88625',
 'U06529',
 'U11422']

In [155]:
df = pd.DataFrame(data[data['매장코드']==cd])
menu = df['상품명']
menulist = dict()
menuName = list(set(df['상품명']))
for m in menuName : menulist[m] = 0
for m in menu :
    if m in menulist.keys() : menulist[m] += 1
    else : print("띠용")
# DATA

In [156]:
menulist

{'마늘전기구이': 56,
 '아이스황도': 4,
 '골뱅이': 35,
 '생맥주 500cc': 663,
 '하이네켄(병)': 1,
 '칭따오': 9,
 '클라우드': 8,
 '참나무통맑은이슬': 2,
 '순살파닭': 59,
 '뉴하이트': 6,
 '마운틴듀': 3,
 '기네스(병)': 4,
 '아사히(병)': 2,
 '쥬스': 2,
 '불사조': 28,
 '메가크런치(M)': 47,
 '처음처럼': 181,
 '웨지포테이토': 10,
 '깐부 마른안주세트': 74,
 '고추간장': 91,
 '버드와이저(생)': 29,
 '한라산': 1,
 '생맥주2700cc': 39,
 '깐부어묵탕': 26,
 '순살스윗': 142,
 '웰치스': 17,
 '웨지포테이토(M)': 12,
 '순살국물떡볶이': 66,
 '윙봉크런치': 61,
 '호가든(병)': 4,
 '깐부먹태': 92,
 '깐부골뱅이(M)': 51,
 '마늘토핑': 4,
 '생맥주1,000cc(포장)': 6,
 '콜라': 168,
 '바삭한식스팩': 101,
 '로스트윙&봉': 53,
 '깐부착한샐러드[메인메뉴주문시]': 10,
 '생맥주1700cc': 47,
 '메가크런치': 27,
 '사이다': 111,
 '마늘간장윙봉크런치': 37,
 '스파이시포테이토': 20,
 '코울슬러': 54,
 '번데기탕': 24,
 '깐부착한샐러드[단품]': 7,
 '추가': 5,
 '선결제10만원': 2,
 '크리스피 반반': 37,
 '깐부소시지': 28,
 '전기구이': 43,
 '스파이시포테이토(M)': 59,
 '유린치킨': 34,
 '크리스피 양념': 4,
 '케이준치킨샐러드': 10,
 '환타(오렌지)': 10,
 '선결제': 2,
 '쫄면사리(추가)': 7,
 '청하': 3,
 '후라이드': 88,
 '파토핑': 1,
 '후라이드 반반': 42,
 '불사조윙봉크런치': 12,
 '크리스피': 70,
 '마늘간장': 94,
 '버드와이저 2+1': 26,
 '카스': 49,
 '후라이드 양념': 8,
 '마늘간장(순살)': 21,
 '선결제1만원': 3,
 '순살크리스피': 157,
 '참이슬': 164}

In [157]:
DATA = dict()
DATA['매장코드'] = [cd] * len(menu)
DATA['매장명'] = [list(df[df['매장코드']==cd]['매장명'])[0]] * len(menu)
DATA['상품명'] = list(menulist.keys())
DATA['팔린 개수'] = list(menulist.values())

In [158]:
for cd in CD :
    df = pd.DataFrame(data[data['매장코드']==cd])
    menu = df['상품명']
    menulist = dict()
    for m in list(set(df['상품명'])) : menulist[m] = 0
    for m in menu :
        if m in menulist.keys() : menulist[m] += 1
        else : print("띠용")

    DATA = dict()
    DATA['매장코드'] = [cd] * len(menulist.keys())
    DATA['매장명'] = [list(df[df['매장코드']==cd]['매장명'])[0]] * len(menulist.keys())
    DATA['상품명'] = list(menulist.keys())
    DATA['팔린 개수'] = list(menulist.values())

    # print(len(DATA['매장코드']), len(DATA['매장명']), len(DATA['상품명']), len(DATA['팔린 개수']))
    if cd == CD[0] : menuData = pd.DataFrame(DATA).sort_values(by=['팔린 개수'], axis=0, ascending=False)
    else : menuData = menuData.append(pd.DataFrame(DATA).sort_values(by=['팔린 개수'], axis=0, ascending=False), ignore_index=True)

In [159]:
menuData #72

        매장코드               매장명          상품명  팔린 개수
0     S23991  깐부치킨(강남구청역1번출구점)    생맥주 500cc    281
1     S23991  깐부치킨(강남구청역1번출구점)       순살크리스피    143
2     S23991  깐부치킨(강남구청역1번출구점)         후라이드    131
3     S23991  깐부치킨(강남구청역1번출구점)           소주    104
4     S23991  깐부치킨(강남구청역1번출구점)           콜라     98
...      ...               ...          ...    ...
1847  U11422         깐부치킨(청담1)      후라이드 양념      1
1848  U11422         깐부치킨(청담1)      페리에(레몬)      1
1849  U11422         깐부치킨(청담1)          불사조      1
1850  U11422         깐부치킨(청담1)  노아(바나나리치망고)      1
1851  U11422         깐부치킨(청담1)       바삭한식스팩      1

[1852 rows x 4 columns]

In [160]:
menuData.to_csv('../rawdata/깐부치킨_매장별_상품별 팔린 개수.csv', index=False)

In [161]:
test = pd.read_csv('../rawdata/깐부치킨_매장별_상품별 팔린 개수.csv', encoding='UTF8')
test

        매장코드               매장명          상품명  팔린 개수
0     S23991  깐부치킨(강남구청역1번출구점)    생맥주 500cc    281
1     S23991  깐부치킨(강남구청역1번출구점)       순살크리스피    143
2     S23991  깐부치킨(강남구청역1번출구점)         후라이드    131
3     S23991  깐부치킨(강남구청역1번출구점)           소주    104
4     S23991  깐부치킨(강남구청역1번출구점)           콜라     98
...      ...               ...          ...    ...
1847  U11422         깐부치킨(청담1)      후라이드 양념      1
1848  U11422         깐부치킨(청담1)      페리에(레몬)      1
1849  U11422         깐부치킨(청담1)          불사조      1
1850  U11422         깐부치킨(청담1)  노아(바나나리치망고)      1
1851  U11422         깐부치킨(청담1)       바삭한식스팩      1

[1852 rows x 4 columns]