In [2]:
import pandas as pd

# 예린, 서연 파일 경로 (22.06.05 서연 파일 경로 예린과 통일)
#sy_file = "../../rawdata/"
sy_file = "../../../resources/rawdata/"

# 변수명이 애매하므로 수정 (22.06.15 예린)
store_info = pd.read_csv(sy_file+'매장데이터_수정.csv', encoding='UTF8')
sales = pd.read_csv(sy_file+'거래데이터_full.csv', encoding='UTF8')

c:\Users\dksle\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py:3166: DtypeWarning: Columns (5,9) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
store_info

,매장코드,매장명,매장주소,본사코드,본사명,업태명,종목명,상포명,구분
0,S05987,미소야 개포점,서울특별시 강남구 개포동,H132,(주)보우앤파트너스,음식,분식,미소야 개포점,식당
1,S06024,포메인수서점,서울특별시 강남구 광평로51길 6-11,H154,(주) 에스알인베스,음식,베트남쌀국수,포메인수서점,식당
2,S06249,미소야 일원점,서울특별시 강남구 일원동,H132,(주)보우앤파트너스,음식,분식,미소야 일원점,식당
3,S06883,버드나무집(역삼점),서울특별시 강남구 역삼동,H156,버드나무집,음식,한식,버드나무집(역삼점),식당
4,S07185,미소야 대치점,서울특별시 강남구 대치동,H132,(주)보우앤파트너스,음식,간이음식,미소야 대치점,식당
...,...,...,...,...,...,...,...,...,...
2406,U13785,주식회사 바잇미,서울 강남구 신사동 517-31,0000,단독매장,기타,기타,카페 바잇미,카페
2407,U13883,탠커피앤비어,서울 강남구 강남대로102길 13 (역삼동),0000,단독매장,음식,커피,탠커피앤비어,식당
2408,U14017,의정부오뎅부대찌개(청담점),서울 강남구 청담동 131-10,0000,단독매장,음식,한식,의정부오뎅부대찌개(청담점),식당
2409,U14189,주식회사핑크컬쳐,서울 강남구 강남대로156길 46 (신사동),0000,단독매장,서비스업,전문디자인업,주식회사핑크컬쳐,비식당
2410,U14245,술술풀리는포차,서울 강남구 일원로9길 48 (일원동),0000,단독매장,음식점,일반음식점,술술풀리는포차,식당

In [4]:
from collections import Counter

#본사코드 별 등장 횟수 카운트
CD = store_info['본사코드']
head_counter = Counter(CD)

head_counter

Counter({'H132': 7,
         'H154': 2,
         'H156': 1,
         '0000': 1701,
         'H234': 1,
         'H523': 1,
         'H484': 4,
         'H399': 2,
         'H255': 1,
         'H257': 1,
         'H591': 1,
         'H634': 1,
         'HABW': 1,
         'HADV': 1,
         'HAET': 2,
         'H579': 1,
         'HASB': 1,
         'HAUE': 1,
         'HBAS': 34,
         'HBGJ': 1,
         'HBCF': 6,
         'HBJT': 1,
         'HBIG': 1,
         'HBQL': 1,
         'HBTX': 1,
         'HBOV': 1,
         'HBYT': 1,
         'HBTK': 4,
         'HCGM': 1,
         'HCBW': 2,
         'HCHI': 1,
         'HBZG': 1,
         'HCHV': 4,
         'HCJH': 1,
         'HCLK': 1,
         'H798': 1,
         'HCPX': 1,
         'HCSX': 3,
         'HABF': 1,
         'HBHI': 2,
         'HCEL': 1,
         'HCCZ': 1,
         'HCQW': 1,
         'HBMA': 4,
         'HDHN': 1,
         'HDKC': 1,
         'HDMN': 1,
         'HBJW': 2,
         'HCRG': 1,
         'HAFO': 2,
         'H131': 3,
         'HDKN': 6,
         'HDPV': 1,
         'HDLD': 2,
         'HDBN': 1,
         'HDSF': 18,
         'HDWB': 1,
         'HDWI': 1,
         'HEBN': 3,
         'HDST': 1,
         'HDIF': 2,
         'H921': 1,
         'HDMO': 1,
         'HCYO': 1,
         'HCPF': 1,
         'HEGF': 2,
         'HEGN': 1,
         'HCFZ': 1,
         'HEHI': 1,
         'HDNS': 1,
         'HCTJ': 1,
         'HCBS': 1,
         'HCJS': 1,
         'HEJP': 5,
         'HELQ': 1,
         'HDRK': 6,
         'HESD': 1,
         'HESH': 1,
         'HEZD': 2,
         'HFBB': 1,
         'HEYO': 1,
         'HFDJ': 3,
         'HFDN': 2,
         'HAPR': 1,
         'HEQJ': 1,
         'HFHF': 1,
         'HBLX': 1,
         'HFKQ': 1,
         'HFMQ': 1,
         'HEUE': 5,
         'HFPD': 2,
         'HEQH': 1,
         'HFPR': 6,
         'HETM': 1,
         'HABS': 1,
         'HFRY': 2,
         'HFQT': 1,
         'HDFK': 1,
         'HCWD': 1,
         'HFXB': 1,
         'HFWY': 2,
         'HFXW': 1,
         'HFVT': 1,
         'HFRJ': 1,
         'HFZH': 1,
         'HFZO': 1,
         'HGAG': 5,
         'HFTO': 1,
         'HDOJ': 1,
         'HFWF': 5,
         'HGDA': 1,
         'HFTS': 1,
         'HEFA': 10,
         'HGFN': 1,
         'HGFR': 2,
         'HGFQ': 2,
         'HGCK': 1,
         'HGGA': 2,
         'HGEI': 1,
         'HGEU': 1,
         'HGHQ': 4,
         'HGBE': 1,
         'HGIJ': 1,
         'HGIW': 1,
         'HGJO': 1,
         'HGNO': 1,
         'HGOI': 2,
         'HGOU': 1,
         'HGPY': 1,
         'HGGP': 1,
         'HGSL': 2,
         'HGAS': 1,
         'HGWE': 7,
         'HEPZ': 1,
         'HCZU': 1,
         'HGUQ': 6,
         'HGZI': 1,
         'HGVV': 1,
         'HHAE': 1,
         'HHAM': 2,
         'HGVT': 10,
         'HERJ': 1,
         'HCKO': 1,
         'HHBK': 1,
         'HHBL': 1,
         'HHER': 1,
         'HFZL': 1,
         'HESI': 6,
         'HHFY': 2,
         'HEVR': 1,
         'HHGP': 1,
         'HHGS': 1,
         'HHLT': 1,
         'HFUN': 2,
         'HHAQ': 2,
         'HHNN': 5,
         'HGBQ': 1,
         'HHQV': 2,
         'HECM': 1,
         'HHSO': 1,
         'HHSW': 2,
         'HGPT': 1,
         'HHUF': 1,
         'HEJA': 1,
         'HHTW': 3,
         'HHVM': 1,
         'HHWQ': 3,
         'HHWR': 1,
         'HGHU': 1,
         'HHVO': 7,
         'HCFX': 1,
         'HHOV': 3,
         'HIBH': 2,
         'HHEI': 1,
         'HIDU': 1,
         'HFYV': 1,
         'HHDY': 1,
         'HIEV': 4,
         'HIDL': 1,
         'HBRP': 1,
         'HIHD': 1,
         'HHWU': 2,
         'HHXB': 1,
         'HIAB': 4,
         'HGMS': 2,
         'HIOK': 2,
         'HIOT': 1,
         'HDPN': 1,
         'HIQC': 2,
         'HITA': 1,
         'HGFL': 1,
         'HGLZ': 1,
         'HIVQ': 1,
         'HHCH': 1,
         'HHVX': 1,
         'HIXT': 1,
         'HIYD': 1,
         'HIJE': 7,
         'HIXZ': 1,
         'HGAL': 1,
         'HILX': 1,
         'HIBC': 1,
         'HJBD': 2,
         'HJBE': 2,
         'HFEP': 2,
         'HIYC': 2,
         'HAHP': 1,
         'HJFG': 1,
         'HJGL': 1,
         'HJFX': 7,
         'HGOQ': 7,
         'HHTS': 1,
         'HJIM': 2,
         'HJIN': 1,
         'HJJE': 1,
         'HIMK': 1,
         'HJJO': 6,
         'HJJW': 1,
         'HJKD': 1,
         'HJIH': 1,
         'HJMF': 1,
         'HJFC': 2,
         'HJMU': 1,
         'HIZC': 3,
         'HEZL': 1,
         'HJPX': 1,
         'HDSN': 1,
         'HJRY': 2,
         'HERR': 1,
         'HJNT': 1,
         'HJSQ': 4,
         'HJRE': 2,
         'HHXQ': 1,
         'HJXH': 1,
         'HIYQ': 3,
         'HGDT': 2,
         'HFOV': 1,
         'HJQI': 1,
         'HIFS': 1,
         'HJYN': 1,
         'HFHA': 2,
         'HHNH': 2,
         'HGGO': 1,
         'HJZE': 2,
         'HKBP': 1,
         'HKCK': 1,
         'HJPO': 1,
         'HKDC': 1,
         'HJFR': 1,
         'HKGR': 4,
         'HKHZ': 1,
         'HJBP': 1,
         'HKIQ': 1,
         'HJQE': 1,
         'HKJQ': 1,
         'H222': 2,
         'HHRE': 1,
         'HKKH': 2,
         'HKLM': 1,
         'HKMN': 1,
         'HHZJ': 1,
         'HIIX': 4,
         'HEWC': 1,
         'HIGH': 3,
         'HKPO': 1,
         'HKQR': 2,
         'HEYW': 1,
         'HKCP': 1,
         'HJPA': 1,
         'HKSE': 1,
         'HKTS': 1,
         'HKLI': 3,
         'HIFX': 1,
         'HKWQ': 1,
         'HKJG': 1,
         'HKXB': 1,
         'HKSU': 1,
         'HIWI': 1,
         'HKFZ': 1,
         'HJTS': 2,
         'HKYS': 1,
         'HKZK': 1,
         'HKZL': 1,
         'HKRU': 1,
         'HKGL': 1,
         'HLAG': 1,
         'HLAK': 1,
         'HAIQ': 1,
         'HEAC': 1,
         'HIGO': 1,
         'HLCQ': 1,
         'HLDL': 2,
         'HLEG': 1,
         'HGFP': 1,
         'HKQQ': 1,
         'HLCO': 3,
         'HLGP': 1,
         'H836': 1,
         'HHQL': 1,
         'HLHM': 1,
         'HLIF': 2,
         'HLIN': 1,
         'HLGZ': 1,
         'HLKE': 1,
         'HAAD': 1,
         'HLHS': 1,
         'HLMI': 2,
         'HKHS': 1,
         'HGZG': 1,
         'HDVU': 2,
         'HLMU': 1,
         'HLJQ': 1,
         'HKKQ': 2,
         'HLRE': 1,
         'HLNI': 1,
         'HLRV': 1,
         'HCYK': 1,
         'HJIP': 1,
         'HLPA': 2,
         'HLTF': 2,
         'HLTY': 1,
         'HLVP': 1,
         'HLSX': 1,
         'HKMM': 1,
         'HJKG': 1,
         'HLXE': 1,
         'HIDK': 1,
         'HHQG': 1,
         'HLKF': 2,
         'HLYX': 1,
         'HLUT': 1,
         'HFOM': 1,
         'HMAI': 1,
         'HHHN': 1,
         'HKZM': 1,
         'HKAO': 1,
         'HGSE': 1,
         'HMCE': 1,
         'HJJT': 1,
         'HMBA': 1,
         'HIXE': 1,
         'HLZL': 1,
         'HMEP': 1,
         'HEII': 1,
         'HDAU': 1,
         'HMFI': 1,
         'HKJY': 1,
         'HKBH': 1,
         'HMFU': 2,
         'HDUJ': 1,
         'HHQX': 1,
         'HMIJ': 3,
         'HIQG': 6,
         'HMKC': 1,
         'HGXZ': 1,
         'HMKP': 1,
         'HMKN': 2,
         'HMMP': 1,
         'HLPW': 1,
         'HMMW': 1,
         'HKBS': 1,
         'HMOK': 1,
         'HCYB': 1,
         'HMPK': 2,
         'HMPG': 2,
         'HMPW': 1,
         'HMPZ': 1,
         'HMIE': 1,
         'HMQL': 1,
         'HFWB': 1,
         'HBNR': 3,
         'HMOJ': 2,
         'HDWM': 1,
         'HMIH': 5,
         'HMRZ': 1,
         'HMSD': 2,
         'HLCY': 1,
         'HMRV': 2,
         'HMTC': 2,
         'HMRX': 1,
         'HJRK': 1,
         'HMTT': 1,
         'HMUG': 1,
         'HMVK': 3,
         'HLQI': 1,
         'HMVO': 1,
         'HMWH': 2,
         'HLFF': 1,
         'HMZD': 1,
         'HMXZ': 1,
         'HMQV': 1,
         'HNAD': 1,
         'HMNM': 1,
         'HNBB': 2,
         'HMHJ': 1,
         'HLCD': 1,
         'HNBS': 2,
         'HNCQ': 1,
         'HEPH': 1,
         'HNDF': 1,
         'HNDL': 2,
         'HLBF': 1,
         'HNDR': 1,
         'HNDQ': 1,
         'HNEC': 1,
         'HNDZ': 1,
         'HNEF': 3,
         'HMFG': 1,
         'HNEO': 1,
         'HLLT': 1,
         'HHSP': 1,
         'HFQK': 1,
         'HMML': 1,
         'HMLF': 1})

In [5]:
#본사코드 중 등장 횟수가 5 이상인 것만 head_counter_sorted에 저장
head_counter_sorted = dict()
for key in head_counter.keys() :     
        if head_counter[key] >= 5 : head_counter_sorted[key] = head_counter[key]

head_counter_sorted

{'H132': 7,
 '0000': 1701,
 'HBAS': 34,
 'HBCF': 6,
 'HDKN': 6,
 'HDSF': 18,
 'HEJP': 5,
 'HDRK': 6,
 'HEUE': 5,
 'HFPR': 6,
 'HGAG': 5,
 'HFWF': 5,
 'HEFA': 10,
 'HGWE': 7,
 'HGUQ': 6,
 'HGVT': 10,
 'HESI': 6,
 'HHNN': 5,
 'HHVO': 7,
 'HIJE': 7,
 'HJFX': 7,
 'HGOQ': 7,
 'HJJO': 6,
 'HIQG': 6,
 'HMIH': 5}

In [6]:
# store_info 에서 본사코드가 0000이면 개인 사업자임
# 따라서, 0000 제거하고 프랜차이즈만 소팅
idx = store_info[store_info['본사코드'] == '0000'].index
franchise_store_info = store_info.drop(idx)
franchise_store_info

,매장코드,매장명,매장주소,본사코드,본사명,업태명,종목명,상포명,구분
0,S05987,미소야 개포점,서울특별시 강남구 개포동,H132,(주)보우앤파트너스,음식,분식,미소야 개포점,식당
1,S06024,포메인수서점,서울특별시 강남구 광평로51길 6-11,H154,(주) 에스알인베스,음식,베트남쌀국수,포메인수서점,식당
2,S06249,미소야 일원점,서울특별시 강남구 일원동,H132,(주)보우앤파트너스,음식,분식,미소야 일원점,식당
3,S06883,버드나무집(역삼점),서울특별시 강남구 역삼동,H156,버드나무집,음식,한식,버드나무집(역삼점),식당
4,S07185,미소야 대치점,서울특별시 강남구 대치동,H132,(주)보우앤파트너스,음식,간이음식,미소야 대치점,식당
...,...,...,...,...,...,...,...,...,...
2389,U12955,강창구찹쌀진순대 대치점,서울 강남구 삼성로85길 33 (대치동),HHSP,(주)창구식품,음식,한식,강창구찹쌀진순대 대치점,식당
2393,U13167,산쪼메(압구정접),서울 강남구 논현로175길 11 (신사동),HFQK,주식회사 산쪼메,음식점업,일식,산쪼메(압구정점),식당
2394,U13193,비비드안경,서울 강남구 선릉로 414 (대치동),HMML,(주)코코엘,소매,안경,비비드안경,비식당
2399,U13302,(주)큐브스퀘어101 청담점,"서울 강남구 도산대로49길 11 (신사동, IVY빌딩)",HMLF,주식회사 큐브스퀘어101,음식,카페,(주)큐브스퀘어101 청담점,식당
2405,U13780,아임플라스틱 역삼,서울 강남구 언주로93길 16 (역삼동),HNBB,예그리나,기타,기타,아임플라스틱역삼,비식당

In [8]:
## 매머드커피 가맹점 갯수 count - 총 18개
# 매머드커피 본사코드 == 'HDSF'
len(franchise_store_info[franchise_store_info['본사코드'] == 'HDSF'])

18

In [9]:
franchise_store_info[franchise_store_info['본사코드'] == 'HDSF']["매장명"].unique()

array(['MMTH 역삼점', 'MMTH 강남1호', 'MMTH 청담', 'MMTH 코엑스', 'MMTH 테헤란점',
       'MMTH 현대사옥점', 'MMTH 강남구청', 'MMTH 논현점', 'MMTH 강남역점', 'MMTH 선정릉점',
       'MMTH 선릉점', 'MMTH 신사점', 'MMTH 삼성역점', 'MMTH 국기원점', 'MMTH 역삼역점',
       'MMTH 강남대로점', 'MMTH 한티역점(122호)', 'MMTH 역삼GFC점'], dtype=object)

In [24]:
# 개인 매장 데이터 추출
sales[sales['본사코드'] == '0000'].to_csv('../../../resources/개인매장_거래데이터.csv', index=False)

In [4]:
sales

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
0,T57457,라공방,20190203,238,20190203211944,포장,14000,메뉴,꿔바러우(소),28,1,14000
1,T57457,라공방,20190203,190,20190203185755,포장,14000,메뉴,꿔바러우(소),28,1,14000
2,T57457,라공방,20190203,186,20190203184828,포장,14000,메뉴,꿔바러우(소),28,1,14000
3,T57457,라공방,20190203,184,20190203183953,포장,14000,메뉴,꿔바러우(소),28,1,14000
4,T57457,라공방,20190203,165,20190203175304,포장,14000,메뉴,꿔바러우(소),28,1,14000
...,...,...,...,...,...,...,...,...,...,...,...,...
5884243,U02589,(주)트레이드빌리지 강남1지점,20190227,43,20190227132202,NaN,15900,B,실버반지,900016,1,15900
5884244,U02589,(주)트레이드빌리지 강남1지점,20190226,148,20190226202432,NaN,31800,B,실버반지,900016,2,15900
5884245,U02589,(주)트레이드빌리지 강남1지점,20190226,141,20190226195845,NaN,15900,B,실버반지,900016,1,15900
5884246,U02589,(주)트레이드빌리지 강남1지점,20190226,44,20190226134120,NaN,15900,B,실버반지,900016,1,15900
5884247,U02589,(주)트레이드빌리지 강남1지점,20190226,43,20190226134059,NaN,15900,B,실버반지,900016,1,15900

In [10]:
# 매머드커피 매장코드 리스트 추출
mamm_CD = list(store_info[store_info['본사코드']=="HDSF"]['매장코드'])

# 매머드커피 데이터만 저장할 dataframe 생성
mamm_df = pd.DataFrame(sales[sales['매장코드']==mamm_CD[0]])  #매장코드 중 첫 번째인 것의 데이터만 추출해 데이터프레임 생성

#매장코드 중 첫 번째를 제외한 나머지를 이전에 생성한 데이터프레임에 추가
for cd in mamm_CD[1:] : 
    mamm_df = mamm_df.append(sales[sales['매장코드']==cd])

mamm_df

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
601314,S53661,MMTH 역삼점,20190201,33,20190201122847,NaN,4300,espresso,헤이즐넛모카(ice),000805,1,4300
601315,S53661,MMTH 역삼점,20190201,35,20190201123850,NaN,4000,espresso,꿀바나라떼(ice),000532,1,4000
601316,S53661,MMTH 역삼점,20190201,25,20190201101708,NaN,3400,espresso,꿀라떼(hot),000297,1,3400
601317,S53661,MMTH 역삼점,20190201,35,20190201123850,NaN,6800,espresso,카페라떼(ice),000021,2,3400
601318,S53661,MMTH 역삼점,20190201,11,20190201085522,NaN,3400,espresso,카페라떼(ice),000021,1,3400
...,...,...,...,...,...,...,...,...,...,...,...,...
5834819,T64222,MMTH 역삼GFC점,20190226,172,20190226155656,NaN,0,행사,GFC)식권대장100%할인,000957,1,0
5834820,T64222,MMTH 역삼GFC점,20190226,138,20190226132017,NaN,0,행사,GFC)식권대장100%할인,000957,1,0
5834821,T64222,MMTH 역삼GFC점,20190226,127,20190226130011,NaN,0,행사,GFC)식권대장100%할인,000957,1,0
5834822,T64222,MMTH 역삼GFC점,20190226,55,20190226100837,NaN,0,행사,GFC)식권대장100%할인,000957,1,0
5834823,T64222,MMTH 역삼GFC점,20190226,44,20190226094243,NaN,0,행사,GFC)식권대장100%할인,000957,1,0

In [11]:
# 매머드커피의 소분류별 메뉴명 출력
for i in mamm_df['소분류명'].unique():
    print(i)
    print(mamm_df[mamm_df['소분류명'] == i]['상품명'].unique())

espresso
['헤이즐넛모카(ice)' '꿀바나라떼(ice)' '꿀라떼(hot)' '카페라떼(ice)' '아메리카노(ice)'
 '매머드커피(ice)' '카페모카(hot)' '카라멜마키아토(hot)' '바닐라라떼(hot)' '카페라떼(hot)'
 '카푸치노(hot)' '아메리카노(hot)' '헤이즐넛커피(hot)' '헤이즐넛모카(hot)' '헤이즐넛커피(ice)'
 '콜드브루(ice)' '스노우 매머드(ice)' '티라미수라떼(ice)' '티라미수라떼(hot)' '꿀라떼(ice)'
 '꿀커피(ice)' '카페모카(ice)' '카라멜마키아토(ice)' '바닐라라떼(ice)' '꿀커피(hot)'
 '아몬드라떼(hot)' '아몬드아메리카노(hot)' '코코넛사이공라떼(ice)' '아몬드크림콜드브루(ice)'
 '꿀바나라떼(hot)' '아몬드라떼(ice)' '코코넛사이공라떼(hot)' '콜드브루(hot)' '카푸치노(ice)'
 '아몬드아메리카노(ice)' '레몬토닉콜드브루(ice)' '[S]아몬드라떼(ICE)' '[S]코코넛사이공라떼(HOT)'
 '[S]코코넛사이공라떼(ICE)' '[S]꿀라떼(ICE)' '[S]꿀라떼(HOT)' '[S]헤이즐넛모카(ICE)'
 '[S]카페모카(ICE)' '[S]카페모카(HOT)' '[S]아몬드라떼(HOT)' '[S]아메리카노(HOT)'
 '[S]꿀커피(ICE)' '[S]카페라떼(HOT)' '[S]카라멜마끼아또(ICE)' '[M]카페모카(ICE)'
 '[S]카라멜마끼아또(HOT)' '[S]바닐라라떼(ICE)' '[S]바닐라라떼(HOT)' '[M]바닐라라떼(ICE)'
 '[S]카푸치노(HOT)' '[S]꿀커피(HOT)' '[S]헤이즐넛모카(HOT)' '[S]아몬드아메리카노(HOT)'
 '[S]헤이즐넛커피(ICE)' '[S]아메리카노(ICE)' '[S]꿀바나라떼(HOT)' '[S]카페라떼(ICE)'
 '[S]티라미수라떼(ICE)' '[S]꿀바나라떼(ICE)' '[S]헤이즐넛커피(HOT)' '[S]티라미수라떼(HOT)'
 '[M]티라미수라떼(ICE)' '[M]아메리카노(HOT)' '[S]아몬드아메리카노(ICE)' '에스프레소(hot)'
 '[M]꿀커피(ICE)' '[M]티라미수라떼(HOT)' '[M]카페라떼(ICE)' '[M]아몬드아메리카노(ICE)'
 '[M]아메리카노(ICE)' '[M]아몬드아메리카노(HOT)' '[M]카라멜마끼아또(ICE)' '[M]헤이즐넛커피(ICE)'
 '화이트초콜릿모카(ice)' '화이트초콜릿모카(hot)' '에스프레소(ice)' '슈크림라떼(ice)']
Other Beverage
['차이티라떼(ice)' '그린티라떼(ice)' '그린티라떼(hot)' '콩가루라떼(hot)' '고구마라떼(hot)'
 '초코라떼(ice)' '초코라떼(hot)' '콩가루라떼(ice)' '메론바나라떼(hot)' '차이티라떼(hot)'
 '고구마라떼(ice)' 'S화이트초콜릿라떼(hot)' '[S]딸기크림라떼(ICE)' '[S]초코라떼(HOT)'
 '[S]초코라떼(ICE)' '[S]그린티라떼(HOT)' '[S]콩가루라떼(ICE)' '[S]차이티라떼(HOT)'
 '[S]콩가루라떼(HOT)' '[M]메론바나라떼(ICE)' '[S]메론바나라떼(ICE)' '[S]그린티라떼(ICE)'
 '[S]고구마라떼(HOT)' '[M]초코라떼(ICE)' '[M]딸기크림라떼(ICE)' '[S]옥수수라떼(HOT)'
 '[S]고구마라떼(ICE)' '[M]옥수수라떼(ICE)' 'S화이트초콜릿라떼(ice)' '[S]차이티라떼(ICE)'
 '딸기크림라떼(ice)' '오레오민트초코라떼(ice)' '옥수수라떼(hot)' '그린민트초코라떼(hot)' '옥수수라떼(ice)'
 '리얼쇼콜라떼(ice)' '메론바나라떼(ice)' '그린민트초코라떼(ice)' '오레오민트초코라떼(hot)'
 '리얼쇼콜라떼(hot)' '화이트초코라떼(ice)' '화이트초코라떼(hot)']
Frappe
['자바칩 프라페' '피스타치오 프라페' '쿠키 앤 크림 프라페' '[S]쿠앤크프라페' 'S화이트초콜릿프라페' '[S]자바칩프라페'
 '[S]그린티프라페' '[S]스트로베리바닐라프라페' '[S]피스타치오프라페' '[M]스트로베리바닐라프라페' '솜사탕쉐이크'
 '스트로베리 바닐라 프라페' '그린티 프라페' '그린민트초코 프라페' '카라멜치즈프라페']
Hub&Black Tea
['리얼 레몬티(hot)' '페퍼민트 라임티(hot)' '밀크티(hot)' '리얼 레몬티(ice)' '페퍼민트(ice)'
 '레몬 오렌지(hot)' '캐모마일(hot)' '페퍼민트 라임티(ice)' '페퍼민트(hot)' '패션오렌지 아이스티'
 '[S]오렌지아일랜드티(HOT)' '[S]리얼레몬티(HOT)' '[S]페퍼민트(HOT)' '[S]얼그레이(HOT)'
 '[S]카모마일(HOT)' '[S]페퍼민트(ICE)' '[S]밀크티(HOT)' '[S]카모마일(ICE)'
 '[S]레몬오렌지티(HOT)' '[S]오렌지아일랜드티(ICE)' '피치리치홍차아이스티' '뱅쇼(자몽)(Hot)'
 '[S]리얼레몬티(ICE)' '[S]레몬오렌지티(ICE)' '[S]페퍼민트라임티(HOT)' '뱅쇼(오렌지레몬)(Hot)'
 '뱅쇼(오렌지레몬)(Ice)' '레몬 오렌지(ice)' '캐모마일(ice)' '얼그레이(hot)' '오렌지아일랜드티(ice)'
 '오렌지아일랜드티(hot)' '얼그레이(ice)' '뱅쇼(자몽)(Ice)' '복숭아 아이스티']
Fruit Ade&Tea
['착즙 라임주스' '블루레몬에이드(Ade)' '레몬티(Tea)' '자몽에이드(Ade)' '착즙 자몽주스'
 '오미자크랜베리티(hot)' '허니베리 홍초에이드(Ade)' '오렌지에이드(Ade)' '자몽티(Tea)'
 '라임레몬깔라만시에이드(ade)' '오미자크랜베리에이드(ade)' '라임에이드(Ade)' '청포도에이드(Ade)'
 '오렌지티(Tea)' '착즙 오렌지주스' '제주청귤에이드(ade)' '[S]오렌지에이드' '[S]라임레몬깔라만시에이드'
 '[S]자몽티' '[S]유자티' '[S]블루레몬에이드' '[S]오미자크랜베리에이드' '[S]청포도에이드' '[S]자몽에이드'
 '착즙 레몬주스' '제주한라봉티(tea)' '[S]라임에이드' '[S]유자에이드' '[M]블루레몬에이드' '[S]레드불에너지드링크'
 '[M]오미자크랜베리티' '[M]자몽에이드' '제주청귤티(tea)' '[S]오렌지티' '[M]오렌지에이드'
 '강남1)유자티(hot)' '강남1)유자에이드(ade)' '유자에이드(ade)' '인크레드불[에너지드링크](Ade)'
 '코코망고에이드(Ade)' '유자티(hot)' '제주한라봉에이드(ade)' '팬지플라워티에이드(ade)'
 '라임레몬깔라만시티(hot)' '청매실티(ice)' '청매실티(hot)' '라임티(Tea)' '수박주스']
Add
['샷 추가' '두유' '덜달게' '시나몬 빼고' '토핑빼고' '시나몬 추가' '1.5샷' '얼음 적게' '진하게' '연하게'
 '미지근' '뜨겁게' '얼음많이' '시럽제거' '음료' '휘핑' '물빼고' '우유많이' '추가)매머드 꿀' '추가)매머드 아몬드'
 '시럽' '시럽1' '1샷' '우유적게' '레몬추가' '설탕시럽 빼고' '탄산수변경' '전화주문' '물반' '설탕시럽 추가'
 '3샷' '달게' '0.5샷' '시럽2' '슬라이스 제거' '오렌지 추가' '자몽 추가' '컵추가' '매머드컵 추가' '텀블러'
 '더달게' '포장' '꿀빼고' '꿀' '머그잔/유리잔' 'Hall' '물적게' '블루베리토핑' '딸기소스토핑' '얼음추가'
 '진동벨10' '진동벨2' '진동벨4' '진동벨3' '진동벨1' '진동벨7' '진동벨6' '진동벨9' '진동벨8' '진동벨5'
 '진동벨15']
Smoothie&Yogurt
['딸기스무디' '딸기요거트' '복숭아스무디' '블루베리요거트' '플레인요거트' '피넛버터스무디' '[S]플레인요거트'
 '[S]딸기요거트' '[S]딸기스무디' '[S]코코넛커피스무디' '[S]블루베리요거트' '[M]블루베리요거트' '[S]복숭아스무디'
 '[S]복숭아요거트' '[M]솜사탕쉐이크' '자두스무디' '[M]복숭아스무디' '[S]솜사탕쉐이크' '코코넛커피스무디'
 '고흥유자스무디' '복숭아요거트' '체리베리스무디']
행사
['(행사)아메리카노Ice' '(행사)아메리카노Hot' '(행사)꿀커피Ice' '(행사)꿀커피Hot' '국기원)유자에이드(ade)'
 '국기원)초코라떼(ice)' '국기원)바닐라라떼(hot)' '국기원)꿀커피(ice)' '국기원)카페라떼(hot)'
 '국기원)레몬티(ice)' '국기원)꿀커피(hot)' '국기원)꿀라떼(hot)' '국기원)바닐라라떼(ice)'
 '국기원)초코라떼(hot)' '국기원)카페라떼(ice)' '국기원)레몬티(tea)' '국기원)꿀라떼(ice)'
 '국기원)아메리카노(ice)' '국기원)아메리카노(hot)' '국기원)유자티(hot)' 'GFC)식권대장100%할인']
산더미 점심행사
['점심행사)아몬드아메리카노Ice' '점심행사)아몬드아메리카노Hot']
Dessert
['비스킷슈(바닐라)' '비스킷슈(초코)' '바나나쿠키' '브라우니쿠키' '스콘(크랜베리)' '쿠키' '쁘띠마카롱 6종'
 '스콘(블루베리)' '머핀샌드위치' '요거트 아이스크림' 'Ice 아메리카노 Set' '머핀 Set' 'Hot 아메리카노 Set'
 '분다버그-핑크자몽(병)' '창소다워터' '에그샐러드샌드위치' '에그샐러드+아메set' '튜나샐러리샌드위치' '클럽샌드위치'
 '클럽+아메set' '베이컨치즈샌드위치' '베이컨치즈+아메set' '튜나샐러리+아메set' '당근케이크' '까망베르치즈케이크'
 '멜팅치즈 샌드위치' '치킨팟파이' '분다버그-진저비어(병)' '클래식치즈케이크' '골드메달주스(병)' '아쿠아파나(병)'
 '쇼콜라아메르케이크' '레인보우케이크' '마카롱-민트초코' '마카롱-블루베리' '마카롱-바닐라' '마카롱-라즈베리' '마카롱-망고'
 '마카롱-초코' '플레인베이글' '허니브레드' '크림치즈' '블루베리베이글' '로리나(오렌지)' '멜팅치즈 Set'
 '팟파이 Set' '로리나(핑크레몬)' '단호박타르트' '애플시나몬타르트' '화이트치즈케이크' '떠먹는티라미수-화이트'
 '떠먹는티라미수-마스카포네']

In [17]:
mamm_df[mamm_df['소분류명'] == 'espresso']['상품명'].unique()

array(['헤이즐넛모카(ice)', '꿀바나라떼(ice)', '꿀라떼(hot)', '카페라떼(ice)', '아메리카노(ice)',
       '매머드커피(ice)', '카페모카(hot)', '카라멜마키아토(hot)', '바닐라라떼(hot)',
       '카페라떼(hot)', '카푸치노(hot)', '아메리카노(hot)', '헤이즐넛커피(hot)',
       '헤이즐넛모카(hot)', '헤이즐넛커피(ice)', '콜드브루(ice)', '스노우 매머드(ice)',
       '티라미수라떼(ice)', '티라미수라떼(hot)', '꿀라떼(ice)', '꿀커피(ice)', '카페모카(ice)',
       '카라멜마키아토(ice)', '바닐라라떼(ice)', '꿀커피(hot)', '아몬드라떼(hot)',
       '아몬드아메리카노(hot)', '코코넛사이공라떼(ice)', '아몬드크림콜드브루(ice)', '꿀바나라떼(hot)',
       '아몬드라떼(ice)', '코코넛사이공라떼(hot)', '콜드브루(hot)', '카푸치노(ice)',
       '아몬드아메리카노(ice)', '레몬토닉콜드브루(ice)', '[S]아몬드라떼(ICE)',
       '[S]코코넛사이공라떼(HOT)', '[S]코코넛사이공라떼(ICE)', '[S]꿀라떼(ICE)',
       '[S]꿀라떼(HOT)', '[S]헤이즐넛모카(ICE)', '[S]카페모카(ICE)', '[S]카페모카(HOT)',
       '[S]아몬드라떼(HOT)', '[S]아메리카노(HOT)', '[S]꿀커피(ICE)', '[S]카페라떼(HOT)',
       '[S]카라멜마끼아또(ICE)', '[M]카페모카(ICE)', '[S]카라멜마끼아또(HOT)',
       '[S]바닐라라떼(ICE)', '[S]바닐라라떼(HOT)', '[M]바닐라라떼(ICE)', '[S]카푸치노(HOT)',
       '[S]꿀커피(HOT)', '[S]헤이즐넛모카(HOT)', '[S]아몬드아메리카노(HOT)',
       '[S]헤이즐넛커피(ICE)', '[S]아메리카노(ICE)', '[S]꿀바나라떼(HOT)', '[S]카페라떼(ICE)',
       '[S]티라미수라떼(ICE)', '[S]꿀바나라떼(ICE)', '[S]헤이즐넛커피(HOT)',
       '[S]티라미수라떼(HOT)', '[M]티라미수라떼(ICE)', '[M]아메리카노(HOT)',
       '[S]아몬드아메리카노(ICE)', '에스프레소(hot)', '[M]꿀커피(ICE)', '[M]티라미수라떼(HOT)',
       '[M]카페라떼(ICE)', '[M]아몬드아메리카노(ICE)', '[M]아메리카노(ICE)',
       '[M]아몬드아메리카노(HOT)', '[M]카라멜마끼아또(ICE)', '[M]헤이즐넛커피(ICE)',
       '화이트초콜릿모카(ice)', '화이트초콜릿모카(hot)', '에스프레소(ice)', '슈크림라떼(ice)'],
      dtype=object)

In [12]:
mamm_df

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
601314,S53661,MMTH 역삼점,20190201,33,20190201122847,NaN,4300,espresso,헤이즐넛모카(ice),000805,1,4300
601315,S53661,MMTH 역삼점,20190201,35,20190201123850,NaN,4000,espresso,꿀바나라떼(ice),000532,1,4000
601316,S53661,MMTH 역삼점,20190201,25,20190201101708,NaN,3400,espresso,꿀라떼(hot),000297,1,3400
601317,S53661,MMTH 역삼점,20190201,35,20190201123850,NaN,6800,espresso,카페라떼(ice),000021,2,3400
601318,S53661,MMTH 역삼점,20190201,11,20190201085522,NaN,3400,espresso,카페라떼(ice),000021,1,3400
...,...,...,...,...,...,...,...,...,...,...,...,...
5834819,T64222,MMTH 역삼GFC점,20190226,172,20190226155656,NaN,0,행사,GFC)식권대장100%할인,000957,1,0
5834820,T64222,MMTH 역삼GFC점,20190226,138,20190226132017,NaN,0,행사,GFC)식권대장100%할인,000957,1,0
5834821,T64222,MMTH 역삼GFC점,20190226,127,20190226130011,NaN,0,행사,GFC)식권대장100%할인,000957,1,0
5834822,T64222,MMTH 역삼GFC점,20190226,55,20190226100837,NaN,0,행사,GFC)식권대장100%할인,000957,1,0
5834823,T64222,MMTH 역삼GFC점,20190226,44,20190226094243,NaN,0,행사,GFC)식권대장100%할인,000957,1,0

In [13]:
## 매머드커피 거래데이터 csv로 추출
# 파일 경로 수정 processedData -> ExtractedData (22.06.15 예린)
mamm_df.to_csv('../../../resources/extractedData/매머드_거래데이터.csv', encoding="utf8" ,index=False)    #csv로 저장

In [15]:
mamm_df['매장명'].unique()

array(['MMTH 역삼점', 'MMTH 강남1호', 'MMTH 청담', 'MMTH 코엑스', 'MMTH 테헤란점',
       'MMTH 현대사옥점', 'MMTH 강남구청', 'MMTH 논현점', 'MMTH 강남역점', 'MMTH 선정릉점',
       'MMTH 선릉점', 'MMTH 신사점', 'MMTH 삼성역점', 'MMTH 국기원점', 'MMTH 역삼역점',
       'MMTH 강남대로점', 'MMTH 한티역점(122호)', 'MMTH 역삼GFC점'], dtype=object)

In [14]:
# 할인 행사 진행한 강남1호, 국기원, GFC drop
query = (mamm_df['매장명'] == 'MMTH 강남1호') | (mamm_df['매장명'] == 'MMTH 국기원점') | (mamm_df['매장명'] == 'MMTH 역삼GFC점')
idx = mamm_df[query].index
mamm_df2 = mamm_df.drop(idx)
mamm_df2

,매장코드,매장명,영업일자,영수증번호,결제일시,테이블번호,총판매금액,소분류명,상품명,상품코드,판매수량,판매단가
601314,S53661,MMTH 역삼점,20190201,33,20190201122847,NaN,4300,espresso,헤이즐넛모카(ice),000805,1,4300
601315,S53661,MMTH 역삼점,20190201,35,20190201123850,NaN,4000,espresso,꿀바나라떼(ice),000532,1,4000
601316,S53661,MMTH 역삼점,20190201,25,20190201101708,NaN,3400,espresso,꿀라떼(hot),000297,1,3400
601317,S53661,MMTH 역삼점,20190201,35,20190201123850,NaN,6800,espresso,카페라떼(ice),000021,2,3400
601318,S53661,MMTH 역삼점,20190201,11,20190201085522,NaN,3400,espresso,카페라떼(ice),000021,1,3400
...,...,...,...,...,...,...,...,...,...,...,...,...
5871701,T61943,MMTH 한티역점(122호),20190226,32,20190226111455,NaN,0,Add,머그잔/유리잔,654,1,0
5871702,T61943,MMTH 한티역점(122호),20190226,24,20190226103047,NaN,0,Add,머그잔/유리잔,654,1,0
5871703,T61943,MMTH 한티역점(122호),20190226,8,20190226092409,NaN,0,Add,머그잔/유리잔,654,1,0
5871704,T61943,MMTH 한티역점(122호),20190226,4,20190226081742,NaN,0,Add,머그잔/유리잔,654,1,0
5871705,T61943,MMTH 한티역점(122호),20190228,55,20190228122136,NaN,0,Add,덜달게,461,1,0

In [15]:
# 강남1호, 국기원, GFC 지점 drop 한 데이터 추출
# 파일 경로 수정 processedData -> ExtractedData (22.06.15 예린)
mamm_df2.to_csv('../../../resources/extractedData/매머드_거래데이터_1차.csv', index = False)